// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalManagementSystem.Models;

[Table("Billing")]
[Index("ReservationId", Name = "UQ__Billing__B7EE5F255346EF4D", IsUnique = true)]
public partial class Billing
{
    [Key]
    public int BillingId { get; set; }

    public int ReservationId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal BaseAmount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal AdditionalCharges { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    [Required]
    [StringLength(20)]
    public string PaymentStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BillingDate { get; set; }

    [ForeignKey("ReservationId")]
    [InverseProperty("Billing")]
    public virtual Reservation Reservation { get; set; }
}