// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalManagementSystem.Models;

[Index("LicensePlate", Name = "UQ__Vehicles__026BC15C48265E24", IsUnique = true)]
public partial class Vehicle
{
    [Key]
    public int VehicleId { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string Make { get; set; }

    [Required]
    [StringLength(50)]
    public string Model { get; set; }

    public int Year { get; set; }

    [Required]
    [StringLength(20)]
    public string LicensePlate { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    public int Mileage { get; set; }

    [Column(TypeName = "decimal(10,2)")]
    public decimal RatePerDay { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Vehicles")]
    public virtual VehicleCategory Category { get; set; }

    [InverseProperty("Vehicle")]
    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}