// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalManagementSystem.Models;

public partial class VehicleCategory
{
    [Key]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DailyRate { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}